"""
This type stub file was generated by pyright.
"""

from .exceptions import CircularReferenceError, DuplicatedRegistrationError, MappingError
from .mapper import Mapper
from .mapper_initializer import create_mapper

mapper = ...
